### ISSUE TITLE
Anti-Trash New Reddit unblocked advertisement left over on reddit.

### ISSUE THREAD

**Issue by chirag127** [WhyIsEvery4thYearAlwaysBad/anti-cancer-filter-lists#1]
https://github.com/AdguardTeam/AdguardFilters/issues/80559#issuecomment-822434862

![image](https://user-images.githubusercontent.com/76880977/115238622-83b8c980-a13b-11eb-99ff-fbc3703557eb.png)
![image](https://user-images.githubusercontent.com/76880977/115238626-85828d00-a13b-11eb-93aa-f29f54ca77d5.png)

**Comment by WhyIsEvery4thYearAlwaysBad** [comment]
The new reddit site uses a script to generate the site layout, so as a result classes and ids are randomized. Unfortunately the ad box is too generic for a filter to work on it.

Also if you used uBlock Origin, did you purge all caches?
